document.getElementById("navbarr").innerHTML =
"<header>WELCOME</header>"
+"<nav class='navlist'>"
				+"<ul>"
					+"<li><a href='home.php'><i class='fas fa-qrcode'></i> HOME</a></li>"
					+"<li id='dropdown'><a href='#'><i class='fas fa-question-circle'></i>ABOUT</a>"
						+"<ul id='d-menu'>"
						  +"<li><a href='emptest.php'>PERSONAL INFO </a></li>"
						  +"<li><a href='emptest2.php'>BANK INFO</a></li>"
						+"</ul>"  
					+"</li>"
					// +"<li><a href='appli.html'><i class='fas fa-link'></i> APPLICATION</a></li>"
					+"<li><a href='msgpage.php'><i class='fas fa-quote-left'></i>INBOX<span id='message'></span> </a></li>"
					// +"<li><a href='appli.html'><i class='fas fa-link'></i> APPLICATION</a></li>"
					+"<li><a href='../login.php'><i class='fas fa-sign-out-alt'</i> LOGOUT</a></li>"
				+"</ul>"
+"</nav>"